### ISSUE TITLE
Add Ellipsis Mixin

### ISSUE THREAD

**Issue by PaulAdamDavis** [CrossStroke/OriginTheme#10]
More and more often, I need to trim text in cards by the number of lines, so it makes sense for this to exist in core.

```scss
@mixin multi_line_ellipsis($font-size: 26px, $line-height: 1.4, $lines-to-show: 3){
  display: block; /* Fallback for non-webkit */
  display: -webkit-box;
  height: $font-size * $line-height * $lines-to-show;
  margin: 0 auto;
  font-size: $font-size;
  line-height: $line-height;
  -webkit-line-clamp: $lines-to-show;
  -webkit-box-orient: vertical;
  overflow: hidden;
  text-overflow: ellipsis;
}
```
