### ISSUE TITLE
Add `_hacks.scss`

### ISSUE THREAD

**Issue by PaulAdamDavis** [CrossStroke/OriginTheme#6]
There are plenty of shitty functions and classes that don't have a proper home. Let's add a place for shitty hacks.

First up is this, which makes Webkit respect line height in text inputs

``` css
::-webkit-input-placeholder {
    line-height: normal;
}
```

Next up, other shitty hacks that I find looking through old projects.
